version: "2"

services:
  app:
    image: golang:alpine
    ports:
      - "8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=link.gorzsony.com
      - VIRTUAL_PORT=8080
    command: go run -mod=vendor ./cmd/razlink -redis-addr redis:6379

  redis:
    image: redis:alpine
    volumes:
    - ./redis-data:/data
